'\" t
.\"     Title: COMMIT
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2009-12-01
.\"    Manual: PostgreSQL snapshot Documentation
.\"    Source: PostgreSQL snapshot
.\"  Language: English
.\"
.TH "COMMIT" "7" "2009-12-01" "PostgreSQL snapshot" "PostgreSQL snapshot Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
COMMIT \- commit the current transaction
.\" COMMIT
.SH "SYNOPSIS"
.sp
.nf
COMMIT [ WORK | TRANSACTION ]
.fi
.SH "DESCRIPTION"
.PP
COMMIT
commits the current transaction\&. All changes made by the transaction become visible to others and are guaranteed to be durable if a crash occurs\&.
.SH "PARAMETERS"
.PP
WORK, TRANSACTION
.RS 4
Optional key words\&. They have no effect\&.
.RE
.SH "NOTES"
.PP
Use
ROLLBACK
to abort a transaction\&.
.PP
Issuing
COMMIT
when not inside a transaction does no harm, but it will provoke a warning message\&.
.SH "EXAMPLES"
.PP
To commit the current transaction and make all changes permanent:
.sp
.if n \{\
.RS 4
.\}
.nf
COMMIT;
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
The SQL standard only specifies the two forms
COMMIT
and
COMMIT WORK\&. Otherwise, this command is fully conforming\&.
.SH "SEE ALSO"
BEGIN, ROLLBACK
