'\" t
.\"     Title: REASSIGN OWNED
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2009-12-01
.\"    Manual: PostgreSQL snapshot Documentation
.\"    Source: PostgreSQL snapshot
.\"  Language: English
.\"
.TH "REASSIGN OWNED" "7" "2009-12-01" "PostgreSQL snapshot" "PostgreSQL snapshot Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
REASSIGN_OWNED \- change the ownership of database objects owned by a database role
.\" REASSIGN OWNED
.SH "SYNOPSIS"
.sp
.nf
REASSIGN OWNED BY \fIold_role\fR [, \&.\&.\&.] TO \fInew_role\fR
.fi
.SH "DESCRIPTION"
.PP
REASSIGN OWNED
instructs the system to change the ownership of the database objects owned by one of the old_roles, to new_role\&.
.SH "PARAMETERS"
.PP
\fIold_role\fR
.RS 4
The name of a role\&. The ownership of all the objects in the current database owned by this role will be reassigned to
\fInew_role\fR\&.
.RE
.PP
\fInew_role\fR
.RS 4
The name of the role that will be made the new owner of the affected objects\&.
.RE
.SH "NOTES"
.PP
REASSIGN OWNED
is often used to prepare for the removal of one or more roles\&. Because
REASSIGN OWNED
only affects the objects in the current database, it is usually necessary to execute this command in each database that contains objects owned by a role that is to be removed\&.
.PP
The
DROP OWNED
command is an alternative that drops all the database objects owned by one or more roles\&.
.PP
The
REASSIGN OWNED
command does not affect the privileges granted to the old_roles in objects that are not owned by them\&. Use
DROP OWNED
to revoke those privileges\&.
.SH "COMPATIBILITY"
.PP
The
REASSIGN OWNED
statement is a
PostgreSQL
extension\&.
.SH "SEE ALSO"
DROP OWNED, DROP ROLE
