'\" t
.\"     Title: UNLISTEN
.\"    Author: The PostgreSQL Global Development Group
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 2009-12-01
.\"    Manual: PostgreSQL snapshot Documentation
.\"    Source: PostgreSQL snapshot
.\"  Language: English
.\"
.TH "UNLISTEN" "7" "2009-12-01" "PostgreSQL snapshot" "PostgreSQL snapshot Documentation"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
UNLISTEN \- stop listening for a notification
.\" UNLISTEN
.SH "SYNOPSIS"
.sp
.nf
UNLISTEN { \fIname\fR | * }
.fi
.SH "DESCRIPTION"
.PP
UNLISTEN
is used to remove an existing registration for
NOTIFY
events\&.
UNLISTEN
cancels any existing registration of the current
PostgreSQL
session as a listener on the notification
\fIname\fR\&. The special wildcard
*
cancels all listener registrations for the current session\&.
.PP
NOTIFY
contains a more extensive discussion of the use of
LISTEN
and
NOTIFY\&.
.SH "PARAMETERS"
.PP
\fIname\fR
.RS 4
Name of a notification (any identifier)\&.
.RE
.PP
*
.RS 4
All current listen registrations for this session are cleared\&.
.RE
.SH "NOTES"
.PP
You can unlisten something you were not listening for; no warning or error will appear\&.
.PP
At the end of each session,
UNLISTEN *
is automatically executed\&.
.SH "EXAMPLES"
.PP
To make a registration:
.sp
.if n \{\
.RS 4
.\}
.nf
LISTEN virtual;
NOTIFY virtual;
Asynchronous notification "virtual" received from server process with PID 8448\&.
.fi
.if n \{\
.RE
.\}
.PP
Once
UNLISTEN
has been executed, further
NOTIFY
commands will be ignored:
.sp
.if n \{\
.RS 4
.\}
.nf
UNLISTEN virtual;
NOTIFY virtual;
\-\- no NOTIFY event is received
.fi
.if n \{\
.RE
.\}
.SH "COMPATIBILITY"
.PP
There is no
UNLISTEN
command in the SQL standard\&.
.SH "SEE ALSO"
LISTEN, NOTIFY
